name: check
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
      - uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: true
      - run: make
